import { expect, test } from "@playwright/test";

function createDraftFixture() {
  return {
    schemaVersion: 1,
    draftId: `pw_clone_duo_${Date.now()}`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    protocol: "saml",
    blueprintFamily: "generic_saml",
    sourceBundle: {
      sourcePages: [
        {
          id: "source_page_1",
          title: "How to Configure SAML 2.0 for Zoom",
          url: "https://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-2.0-for-Zoom.us.html",
        },
      ],
      evidence: [
        {
          id: "ev_section_1",
          sourcePageId: "source_page_1",
          type: "paragraph_block",
          headingPath: ["Configuration Steps"],
          ordinal: 1,
          text: "Enter the SAML values generated by your IdP into the target application.",
          citationLabel: "Configuration Steps · block 1",
        },
      ],
    },
    sections: [
      {
        sectionId: "update_application_in_duo",
        title: "Update Your Cloud Application in Duo",
        order: 10,
        markdown: "## Update Your Cloud Application in Duo\n\n- Assertion Consumer Service (ACS) URL: UNRESOLVED",
        evidenceIds: ["ev_section_1"],
        unresolvedFieldIds: ["sp_acs_url"],
        screenshotAttachmentIds: ["shot_1"],
      },
    ],
    fields: [
      {
        fieldId: "sp_acs_url",
        label: "Assertion Consumer Service (ACS) URL",
        group: "service_provider",
        targetSectionId: "update_application_in_duo",
        status: "unresolved_needs_user_input",
        value: "",
        expectedFormatHint: "HTTPS ACS endpoint published by the service provider.",
        reviewerHelpText: "The URL where the service provider receives SAML assertions.",
        unresolved: {
          reviewerEnteredValue: "",
          fillPrompt: "Enter assertion consumer service (acs) url",
          rationale: "The public source documentation references this value but does not expose the tenant-specific value directly.",
          recommendedValueOrPattern: "Use the Assertion Consumer Service URL published by the service provider or shown in its SAML metadata.",
        },
      },
    ],
    screenshotAttachments: [
      {
        id: "shot_1",
        sectionId: "update_application_in_duo",
        evidenceId: "ev_section_1",
        attachmentReason: "settings_panel",
        reviewState: "pending",
        exportDisposition: "include_placeholder_note",
      },
    ],
    issues: [
      {
        id: "issue_1",
        severity: "critical",
        type: "missing_required_field",
        fieldId: "sp_acs_url",
        sectionId: "update_application_in_duo",
        summary: "Assertion Consumer Service (ACS) URL needs reviewer attention.",
        recommendation: "Use the Assertion Consumer Service URL published by the service provider or shown in its SAML metadata.",
        blocking: true,
        status: "open",
      },
    ],
    reviewDecisions: [],
    summary: {
      unresolvedFieldCount: 1,
      blockingIssueCount: 1,
      readyToExport: false,
    },
  };
}

test("clone to duo workspace supports keyboard fill-in and screenshot review", async ({ page }) => {
  const draft = createDraftFixture();
  await page.route(`**/api/clone-duo/saml/review-draft/${draft.draftId}`, async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ ok: true, draft }),
    });
  });

  await page.addInitScript((draftId) => {
    localStorage.setItem("sn_clone_duo_draft_id", JSON.stringify(draftId));
  }, draft.draftId);

  await page.goto("/");
  await page.getByRole("button", { name: "Tools" }).click();
  await page.getByLabel("Open Clone to Duo Template").click();
  await expect(page.getByRole("heading", { name: "Clone to Duo Template" })).toBeVisible();

  const fieldInput = page.getByLabel("Fill Assertion Consumer Service (ACS) URL");
  await fieldInput.focus();
  await page.keyboard.type("https://service.example.com/saml/acs");
  await expect(fieldInput).toHaveValue("https://service.example.com/saml/acs");

  await page.keyboard.press("Tab");
  await expect(page.getByLabel("Accept override for Assertion Consumer Service (ACS) URL")).toBeFocused();
  await page.keyboard.press("Enter");
  await expect(page.getByLabel("Fill Assertion Consumer Service (ACS) URL")).toHaveCount(0);
  await expect(page.getByText("https://service.example.com/saml/acs")).toBeVisible();

  const screenshotSelect = page.getByLabel("Screenshot review state settings panel");
  await screenshotSelect.focus();
  await page.keyboard.press("ArrowDown");
  await page.keyboard.press("ArrowDown");
  await expect(screenshotSelect).toHaveValue("replace_later");
});